/* Generated by LLM - DO NOT EDIT */
#ifndef __newtonmenu_H__
#define __newtonmenu_H__

#include <gtk/gtk.h>
#include <libxfce4panel/libxfce4panel.h>
#include <libwnck/libwnck.h> // For WnckScreen and WnckWindow
#include <gio/gio.h>        // For GDBus and GMenuModel
#include <dbusmenu-glib/client.h> // For DbusmenuClient

G_BEGIN_DECLS

typedef struct _newtonmenuPlugin newtonmenuPlugin;

struct _newtonmenuPlugin
{
    XfcePanelPlugin *plugin;

    GtkWidget       *event_box;
    // Changed from GtkToggleButton to GtkMenuButton for dynamic menu model binding
    GtkMenuButton   *button; 
    GtkWidget       *button_box;
    GtkWidget       *icon_image;
    GtkWidget       *label_widget;

    gboolean         display_icon_prop;
    gchar           *icon_name_prop;
    gchar           *label_text_prop;

    gboolean         confirm_logout_prop;
    gboolean         confirm_restart_prop;
    gboolean         confirm_shutdown_prop;
    gboolean         confirm_force_quit_prop;
    
    // New properties for global menu configuration
    gboolean         hide_application_name_prop; // Controls if app name is displayed in global menu
    gchar           *global_menu_title_prop;    // Custom title for global menu when app name is hidden

    // Global Menu related members
    GMenu           *static_newton_menu;    // Holds hardcoded Newton actions as a GMenu
    DbusmenuClient  *app_menu_model;        // Menu model from the active application (a DbusmenuClient)
    GMenuModel      *combined_menu_model;   // The final combined GMenuModel to display

    WnckScreen      *wnck_screen;           // WnckScreen to track active window (owned reference)
    WnckWindow      *active_wnck_window;    // Current active window (owned reference)
    gulong           wnck_active_window_changed_handler_id;

    GDBusConnection *dbus_session_bus;      // D-Bus session bus connection (owned reference)
    GDBusProxy      *appmenu_registrar_proxy; // Proxy for com.canonical.AppMenu.Registrar (owned reference)
    gulong           appmenu_registrar_registered_handler_id;
    gulong           appmenu_registrar_unregistered_handler_id;
};

void newtonmenu_save (XfcePanelPlugin *plugin, newtonmenuPlugin *newtonmenu);
void newtonmenu_update_display (newtonmenuPlugin *newtonmenu);

// New function to update the combined menu model (exposed for external calls like config dialog)
void newtonmenu_update_combined_menu (newtonmenuPlugin *newtonmenu);

G_END_DECLS

#endif /* !__newtonmenu_H__ */